[package]
name = "SpeechForge"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"




[lib]
name = "SpeechForge"
path = "src/lib.rs"
crate-type = ["lib"]



[[bin]]
name = "cv2ljspeech_cli"
path = "src/cli/cv2ljspeech.rs"